apiVersion: apps/v1
kind: Deployment
metadata:
  name: associate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: associate
  template:
    metadata:
      labels:
        app: associate
    spec:
      containers:
        - name: associate
          image: uover822/msr-associate:1
          ports:
            - containerPort: 8005
          env:
            - name: cluster
              valueFrom:
                configMapKeyRef:
                  name: msrconfigmap
                  key: cluster
            - name: app
              valueFrom:
                configMapKeyRef:
                  name: msrconfigmap
                  key: app
            - name: user
              valueFrom:
                configMapKeyRef:
                  name: msrconfigmap
                  key: user
