apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: vols.msr.com
spec:
  defaultCompositionRef:
    name: msr-vol
  group: msr.com
  names:
    kind: Vol
    plural: vols
  claimNames:
    kind: VolClaim
    plural: volclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: ID of this service that other objects will use to refer to it.
              parameters:
                type: object
                properties:
                  namespace:
                    description: The namespace
                    type: string
                    default: production
                  storageClass:
                    description: The storage class name
                    type: string
                  volume:
                    description: The volume name
                    type: string
                  capacity:
                    description: The storage capacity
                    type: string
                  hostPath:
                    description: The host path
                    type: string
                  kubernetesProviderConfigName:
                    description: The name of the Kubernetes provider config (used only with compositions with the label location=remote).
                    type: string
                    default: default
            required:
            - id
            - parameters
          status:
            type: object
            properties:
              host:
                description: The host address of the application
                type: string
    additionalPrinterColumns:
    - name: host
      type: string
      jsonPath: ".status.host"
