
version: '3'

networks:
  msr:
    driver: overlay

services:
  mediator:
    image: msr-mediator:1
    networks:
      - msr
    deploy:
      replicas: 1

  associate:
    image: msr-associate:1
    networks:
      - msr
    deploy:
      replicas: 1

  back:
    image: msr-back:1
    ports:
      - "8000:8000"
    networks:
      - msr
    deploy:
      replicas: 1

  descriptor:
    image: msr-descriptor:1
    networks:
      - msr
    deploy:
      replicas: 1

  properties:
    image: msr-properties:1
    networks:
      - msr
    deploy:
      replicas: 1

  reason:
    image: msr-reason:1
    networks:
      - msr
    deploy:
      replicas: 1

  relation:
    image: msr-relation:1
    networks:
      - msr
    deploy:
      replicas: 1

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - msr
    deploy:
      replicas: 1

  web:
    image: msr-web:1
    ports:
      - "8000:8000"
    networks:
      - msr
    deploy:
      replicas: 1

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    ports:
      - "9200:9200"
    environment:
      "xpack.security.enabled": "false" 
    networks:
      - msr
    deploy:
      replicas: 1

  stats:
    image: msr-graphite-statsd
    ports:
      - "8100:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024" 
      - "8125:8125/udp"
    networks:
      - msr
    deploy:
      replicas: 1

  web:
    image: msr-web:1
    ports:
      - "8000:8000"
    networks:
      - msr
    deploy:
      replicas: 1

  zipkin:
    image: openzipkin/zipkin
    ports:
       - "9411:9411"
    networks:
      - msr
    deploy:
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.0
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
    ports:
      - "5601:5601"
    networks:
      - msr
    deploy:
      replicas: 1

  logstash:
    image: msr-logstash
    ports:
      - "5000:5000/udp"
    command: -f /logstash.conf
    networks:
      - msr
    deploy:
      replicas: 1
