apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
spec:
  name: msr
  annotations:
    meta.crossplane.io/maintainer: John Harrison (@uover822)
    meta.crossplane.io/source: github.com/uover822/msr
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: Application types (frontend, backend, backend with a database, etc.)
    meta.crossplane.io/readme: A Configuration package that defines application types like frontend, backend, backend with a database, etc.
#  package: xpkg.upbound.io/msr/4f21df39ffb5-xpkg:v0.2
  crossplane:
    version: ">=v1.15"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
      version: ">=v0.12.1"
